Add some things for M1s and a bunch more in the brewfile and clean up a few other things

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -30,6 +30,11 @@ append_to_zshrc() {
   fi
 }
 
+# shellcheck disable=SC2154
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
+
 echo "
 __________                   .__
 \______   \ _______  __ ____ |  |_______ ___.__.
@@ -38,12 +43,15 @@ __________                   .__
  |____|_  /\___  >\_/  \___  >____/__|   / ____|
         \/     \/          \/            \/
 "
-exit
 
-# shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+arch=$(uname -m)
+if [ "$arch" == "arm64" ]; then
+  HOMEBREW_PREFIX=/opt/homebrew
 
-set -e
+  /usr/sbin/softwareupdate –install-rosetta –agree-to-license
+else
+  HOMEBREW_PREFIX=/usr/local
+fi
 
 if [ ! -d "$HOME/.bin/" ]; then
   mkdir "$HOME/.bin"
@@ -70,7 +78,7 @@ update_shell() {
 
 case "$SHELL" in
   */zsh)
-    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
+    if [ "$(command -v zsh)" != "$HOMEBREW_PREFIX/bin/zsh" ] ; then
       update_shell
     fi
     ;;
@@ -87,56 +95,68 @@ if ! command -v brew >/dev/null; then
     append_to_zshrc '# recommended by brew doctor'
 
     # shellcheck disable=SC2016
-    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1
+    append_to_zshrc "export PATH=\"$HOMEBREW_PREFIX/bin:$PATH\"" 1
 
-    export PATH="/usr/local/bin:$PATH"
-fi
-
-if brew list | grep -Fq brew-cask; then
-  fancy_echo "Uninstalling old Homebrew-Cask ..."
-  brew uninstall --force brew-cask
+    export PATH="$HOMEBREW_PREFIX/bin:$PATH"
 fi
 
 fancy_echo "Updating Homebrew formulae ..."
 brew update --force # https://github.com/Homebrew/brew/issues/1151
 brew bundle --file=- <<EOF
-tap "homebrew/services"
-tap "universal-ctags/universal-ctags"
-tap "heroku/brew"
+cask_args appdir: '/Applications'
 
-# Unix
-brew "universal-ctags", args: ["HEAD"]
-brew "git"
-brew "openssl"
-brew "rcm"
-brew "reattach-to-user-namespace"
-brew "the_silver_searcher"
-brew "tmux"
-brew "vim"
-brew "watchman"
-brew "zsh"
+tap 'homebrew/cask'
+tap 'homebrew/bundle'
+tap 'heroku/brew'
 
-# Heroku
-brew "heroku/brew/heroku"
+brew 'asdf'
+brew 'bash'
+brew 'bat'
+brew 'coreutils'
+brew 'curl'
+brew 'dockutil'
+brew 'elixir'
+brew 'fd'
+brew 'fzf'
+brew 'git'
+brew 'gnu-sed'
+brew 'gnupg'
+brew 'heroku'
+brew 'htop'
+brew 'hub'
+brew 'hyperfine'
+brew 'jq'
+brew 'less'
+brew 'ncdu'
+brew 'nmap'
+brew 'parallel'
+brew 'pspg'
+brew 'pv'
+brew 'ripgrep'
+brew 'rsync'
+brew 'tmux'
+brew 'vim'
+brew 'wget'
+brew 'zsh'
+brew 'zsh-autosuggestions'
+brew 'zsh-history-substring-search'
+brew 'zsh-syntax-highlighting'
 
-# GitHub
-brew "gh"
-
-# Image manipulation
-brew "imagemagick"
-
-# Programming language prerequisites and package managers
-brew "libyaml" # should come after openssl
-brew "coreutils"
-brew "yarn"
-cask "gpg-suite"
-
-# Databases
-brew "postgres", restart_service: :changed
-brew "redis", restart_service: :changed
+cask '1password'
+cask 'alfred'
+cask 'dash'
+cask 'firefox'
+cask 'google-chrome'
+cask 'iterm2'
+cask 'keybase'
+cask 'ngrok'
+cask 'postgres'
+cask 'slack'
+cask 'visual-studio-code'
+cask 'vlc'
+cask 'zoomus'
 EOF
 
-alias install_asdf_plugin=add_or_update_asdf_plugin
 add_or_update_asdf_plugin() {
   local name="$1"
 
@@ -147,14 +167,11 @@ add_or_update_asdf_plugin() {
   fi
 }
 
-# shellcheck disable=SC1090
-source "$HOME/.asdf/asdf.sh"
 add_or_update_asdf_plugin "erlang"
 add_or_update_asdf_plugin "elixir"
 add_or_update_asdf_plugin "ruby"
 add_or_update_asdf_plugin "nodejs"
-
-gem update --system
+add_or_update_asdf_plugin "dotnet-core"
 
 bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring"
 
